# @title
# CELL 2 — Imports and logging configuration
import logging
import os
import pandas as pd
from typing import List, Dict, Any

# --- Framework Imports ---
from fi.opt.datamappers import BasicDataMapper
from fi.opt.base.evaluator import Evaluator
from fi.opt.utils import setup_logging
from fi.opt.optimizers import RandomSearchOptimizer
from fi.opt.generators import LiteLLMGenerator

# Set your API keys
os.environ["FI_API_KEY"] = "YOUR_API_KEY"
os.environ["FI_SECRET_KEY"] = "YOUR_SECRET_KEY"

# Configure logging
setup_logging(level=logging.INFO, log_to_console=True, log_to_file=True, log_file="agent-opt.log")
logger = logging.getLogger(__name__)

print("✅ All components imported and logging is configured.")


# @title Load dataset from CSV
def load_dataset_from_csv() -> List[Dict[str, Any]]:
    '''Loads dataset from the CSV file.'''
    csv_path = os.path.join(os.path.dirname(__file__), 'dataset.csv')
    df = pd.read_csv(csv_path)
    # Rename 'answer' to 'output' to match expected format
    if 'sql' in df.columns:
        df = df.rename(columns={'question': 'input', 'sql': 'output'})
    
    print("Columns: ", df.columns)
    print("Head: ", df.head())
    return df.to_dict("records")

dataset = load_dataset_from_csv()
print("✅ Dataset loaded from CSV successfully. Here are the first two examples:")
for item in dataset[:2]:
    print(item)



# Set up FutureAGI platform evaluator
# Configure your platform evaluator below


# Configure the platform evaluator
evaluator = Evaluator(
    eval_template="text_to_sql",
    eval_model_name="turing_large", # The judge model on the platform
)

# Data mapper connects model outputs to the judge expectations
# Note: Mapping 'question' as the input since we're evaluating SQL generation quality
data_mapper = BasicDataMapper(
    key_map={
        "input": "input",        # Map our 'question' field to the evaluator's 'input'
        "output": "generated_output" # Map the generator's output to the evaluator's 'output'
    }
)

print("✅ Evaluation strategy defined using FutureAGI's built-in evaluation system.")


# @title Prompt Setup
INITIAL_PROMPT = "Question: {input}\nSQL:" # @param {"type":"string"}
GENERATOR_MODEL = "gpt-4o-mini" # @param {"type":"string"}
TEACHER_MODEL = "gpt-4o" # @param {"type":"string"}

print("✅ Ready to optimize! We will improve `{}`".format(INITIAL_PROMPT))

# Define the initial generator with our prompt
initial_generator = LiteLLMGenerator(
    model=GENERATOR_MODEL,
    prompt_template=INITIAL_PROMPT
)

# Initialize the Random Search optimizer
optimizer = RandomSearchOptimizer(
    generator=initial_generator,
    teacher_model=TEACHER_MODEL,
    num_variations=5  # Generate 5 different versions of our prompt
)

# Print examples of what will be passed to evaluator
print("\n--- Example Data Before Evaluation ---")
for i, example in enumerate(dataset[:2]):  # Show first 2 examples
    input_text = example["input"]
    # The generator expects a dictionary with keys matching the prompt template variables
    generated_output = initial_generator.generate({"input": input_text})
    
    # Show what gets passed to the evaluator
    eval_input = {
        "input": input_text,  # Mapped from dataset's "input" field
        "generated_output": generated_output,  # Generated by the LLM
        "output": example["output"]  # Reference output from dataset
    }
    
    print("\nExample {}:".format(i+1))
    print("Input question: {}".format(input_text))
    print("Generated SQL: {}".format(generated_output))
    print("Reference SQL: {}".format(example["output"]))
    print("Data sent to evaluator: {}".format(eval_input))

# @title
results = optimizer.optimize(
    evaluator=evaluator,
    data_mapper=data_mapper,
    dataset=dataset
)


# @title Analysis of Results
print("--- Optimization Complete ---")
print("Final Score: {:.4f}".format(results.final_score))
print("Best Prompt Found:\n{}".format(results.best_generator.get_prompt_template()))

# @title Iteration History
print("--- All Prompt Variations ---")
for idx, hist in enumerate(results.history):
    print("\n--- Variation {} ---".format(idx+1))
    print("Score: {:.4f}".format(hist.average_score))
    print("Prompt: {}".format(hist.prompt))
